name: test-workflow
on:
  push:
     branches: [ stable ]
     
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alepalu/fdapde-docker-image:latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd test/
        export Eigen3_DIR=/usr/share/cmake/Modules # reguired to let eigen3 work with CMake in alpine
        cmake CMakeLists.txt
        make
    - name: run 
      run: |
        cd test/
        export Eigen3_DIR=/usr/share/cmake/Modules # reguired to let eigen3 work with CMake in alpine
        ./fdapde_test
