name: test-macos-clang
on:
  push:
     branches: [ stable, develop ]
     
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install_deps
      run: |
        brew install eigen
    - name: run_tests
      run: |
        cd test/
        chmod +x run_tests.sh
        ./run_tests.sh --compiler clang
